---
- name: Configure web server
  hosts: web
  become: yes
  vars_files:
    - secrets.yml

  roles:
    - role: tomcat-server
    - role: todo-webapp
    
- name: Configure db server
  hosts: localhost
  become: yes
  vars_files:
    - secrets.yml
  roles:
    #- role: mysql-server
    - role: todolist-db